version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    env_file: .env
    volumes:
      - my-db:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d/
    networks: 
      - default

  adinmo:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    networks: 
      - default

# Names our volume
volumes:
  my-db:
  
networks:
  default:
    driver: bridge
