//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "post_batch")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub time_to_query: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::random_number::Entity")]
    RandomNumber,
}

impl Related<super::random_number::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RandomNumber.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
