//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "random_number")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub number: i32,
    pub post_batch_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::post_batch::Entity",
        from = "Column::PostBatchId",
        to = "super::post_batch::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PostBatch,
}

impl Related<super::post_batch::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PostBatch.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
